pipeline {
    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
               auditTools()
            }
        }
    }
}


void auditTools() {
    sh '''
                  git version
                  java -version
                  python --version
    '''
}
