pipeline {
    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh '''
                  git version
                  java -version
                  python --version
                '''
            }
        }
        stage('Publish') {
            when {
                expression { return params.RC }
            } 
            steps {
                sh 'outputing'
            }
        }
    }
}
